### ISSUE TITLE
Reharvest CKAN portals Q1 2022

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/ckan-metadata#1]

**Comment by Ziiiiing** [comment]
A few steps
-------------
- [x] execute script 
- [x] upload execution results to Repo
- [x] manual edit for spreadsheet ([link to spreadsheet](https://docs.google.com/spreadsheets/d/1W5GAfE5A5aMX0YFdlBG4kR3sqlmNpfvqksTaUralE2s/edit#gid=2061882484))
- [ ] upload to GEOMG


Issues
------------
- `05d-11`: New portal with bad url (http://data.nrri.umn.edu/data/).
- Most of the new items do not have web service links (see details in spreadsheet)

**Comment by karenmajewicz** [comment]
skip 05d-11 for now.
